// Do not edit. This file is machine generated by the Resource DLL Wizard.

library mejedenu;

{ITE} {DFMFileType} {Main.dfm}
{ITE} {DFMFileType} {OpenFileUnit.dfm}
{ITE} {RCFileType} {Win32\Debug\mejedenu_DRC.rc}

{$R 'Main.dfm' 'mainForm:TForm'}
{$R 'OpenFileUnit.dfm' 'openFileForm:TForm'}
{$R 'Win32\Debug\mejedenu_DRC.res' 'Win32\Debug\mejedenu_DRC.rc'}

{$E TRK}

begin
end.
